### ISSUE TITLE
Help!We have some questions about flink-connector-pulsar.

### ISSUE THREAD

**Issue by xyhmnb** [apache/pulsar#16029]
**Describe the bug**
these problems about PulsarSource.
1. use the Exclusive subscribeType .when i start the job ,it can receive messages but not ack messages. i query the topic subscription backlog num is not 0.
2. use the Shared subscribeType . the flink receive the old messages when i restart the job for each time.it show the topic subscription backlog num is 0,but it still receive the old message when the job restart.
3. the subscription backlog num is not 0 when i use the new subscriptionName to connect the pulsar. 

**To Reproduce**
1.create service. i use the docker.
docker run -it -p 6650:6650  -p 8888:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:2.9.2 bin/pulsar standalone
2.pulsar2.9.2，flink1.14，flink-connector-pulsar1.14.4
3.test
`StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        PulsarSource<String> source = PulsarSource.builder()
                .setServiceUrl("pulsar://47.102.192.43:6650")
                .setAdminUrl("http://47.102.192.43:8888")
                .setStartCursor(StartCursor.earliest())
                .setTopics("dev-message")
                .setDeserializationSchema(PulsarDeserializationSchema.flinkSchema(new SimpleStringSchema()))
                .setSubscriptionName("flink-subscription")
                .setSubscriptionType(SubscriptionType.Exclusive)
                .build();
        DataStreamSource<String> dataStreamSource = env.fromSource(source,
                WatermarkStrategy.noWatermarks(), "Pulsar Source Work");
        dataStreamSource.print();
        try {
            env.execute("pulsar");
        } catch (Exception e) {
            e.printStackTrace();
        }`

**Expected behavior**
params:
serviceUrl: pulsar://47.102.192.43:6650
adminUrl: http://47.102.192.43:8888
topic: dev-message
transactionCoordinatorEnabled: false
acknowledgmentAtBatchIndexLevelEnabled: false

**Screenshots**
![image](https://user-images.githubusercontent.com/30762020/173271120-a0c08588-d288-4168-80be-4f52634daaf7.png)
![image](https://user-images.githubusercontent.com/30762020/173271177-753374c7-c88d-4e06-ab2f-9d13218d61ee.png)
the message was print but not ack.

**Comment by xyhmnb** [comment]
@Technoboy-  hello, can you help me?

**Comment by Technoboy-** [comment]
> @Technoboy- hello, can you help me?

Sure, I will take a look and reply later.

**Comment by Technoboy-** [comment]
Hi @xyhmnb 
We have fixed a bug that may cause the reader not ack the message (#12853). The root cause is that: when ack, PersistentAcknowledgmentsGroupingTracker#`lastCumulativeAck` may recycle by another thread, so it may cause an NPE exception thrown by flushTask and stop continuing to execute. 

Could you upgrade to flink-connector-pulsar 1.15.0 ?

**Comment by xyhmnb** [comment]
@Technoboy- sure~ ,but I always use this 1.15.0 version. These problems still exist.

**Comment by Technoboy-** [comment]
> @Technoboy- sure~ ,but I always use this 1.15.0 version. These problems still exist.

Yes, right.  After discussing it, we find that the problem still exists.  We will push a fix later.  Very thanks for reporting this.

**Comment by syhily** [comment]
`flink-connector-pulsar` has added a workaround for this situation. Check the code [here](https://github.com/streamnative/flink/tree/feature/new-seek-lifecycle).

**Comment by Technoboy-** [comment]
Fixed by https://github.com/apache/pulsar/pull/16072
