### ISSUE TITLE
[Bug] CI: pulsar does not run tests with interceptors enabled

### ISSUE THREAD

**Issue by dlg99** [apache/pulsar#20091]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

3.0 RC 1

### Minimal reproduce step

similar to https://github.com/apache/pulsar/issues/20071

See https://lists.apache.org/thread/f2fhvyx202xzxbho909j430h63yvwjlo

### What did you expect to see?

Regression caught on CI

### What did you see instead?

regression caught outside of CI

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by cbornet** [comment]
Is this fixed by https://github.com/apache/pulsar/pull/20127 ?

**Comment by dlg99** [comment]
@cbornet the fix you linked (BK upgrade) fixes the rootcause of the last issue we found, the issue is that we don't run integration-level test of pulsar + interceptors. 
The issue is not fixed but I don't think it is a release blocker

**Comment by michaeljmarshall** [comment]
Multiple contributors verified the fix, which is sufficient to unblock the release, in my opinion. We should follow up soon and add a test that enables the broker interceptors.

**Comment by MMirelli** [comment]
I can try to add the test. Should it be an integration test like this one: https://github.com/MMirelli/pulsar/pull/2?

**Comment by tisonkun** [comment]
> I can try to add the test. Should it be an integration test like this one: https://github.com/MMirelli/pulsar/pull/2?

This looks a good example.
